CREATE TABLE `BILL_OF_LADINGS` (
  `ID` int(11) NOT NULL,
  `CUSTOMER_ID` varchar(45) DEFAULT NULL,
  `BILL_OF_LADING` varchar(20) DEFAULT NULL,
  `HOUSE_BILL` varchar(20) DEFAULT NULL,
  `MASTER_BILL` varchar(20) DEFAULT NULL,
  `SCAC_CODE` varchar(5) DEFAULT NULL,
  `CONTAINERS` varchar(1000) DEFAULT NULL,
  `SHIPPER_ID` varchar(15) DEFAULT NULL,
  `MANUFACTURER_ID` varchar(15) DEFAULT NULL,
  `CONSIGNEE_ID` varchar(15) DEFAULT NULL,
  `NOTIFY_PARTY_ID` varchar(15) DEFAULT NULL,
  `NOTIFY_PARTY2_ID` varchar(15) DEFAULT NULL,
  `PRECARRIER_NAME` varchar(50) DEFAULT NULL,
  `CARRIER_NAME` varchar(50) DEFAULT NULL,
  `START_PORT` varchar(45) DEFAULT NULL,
  `END_PORT` varchar(45) DEFAULT NULL,
  `FINAL_DELIVERY` varchar(45) DEFAULT NULL,
  `ETD` varchar(15) DEFAULT NULL,
  `ETD_TIMEZONE` varchar(45) DEFAULT NULL,
  `ETA` varchar(15) DEFAULT NULL,
  `ETA_TIMEZONE` varchar(45) DEFAULT NULL,
  `PLACE_ISSUED` varchar(45) DEFAULT NULL,
  `DATE_ISSUED` varchar(15) DEFAULT NULL,
  `CREATED_AT` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `BOL_CONTAINERS` (
  `ID` int(11) NOT NULL,
  `BILL_OF_LADING_ID` int(11) NOT NULL,
  `CONTAINER` varchar(45) DEFAULT NULL,
  `SIZE` varchar(45) DEFAULT NULL,
  `SEAL` varchar(45) DEFAULT NULL,
  `GROSS_WEIGHT` varchar(20) DEFAULT NULL,
  `VOLUME` varchar(20) DEFAULT NULL,
  `GOODS_DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`,`BILL_OF_LADING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

/* ================================================================= */
CREATE TABLE `DOCUMENTS` (
  `ID` int(11) NOT NULL,
  `CUSTOMER_ID` varchar(45) DEFAULT NULL,
  `DOCUMENT_ID` varchar(45) DEFAULT NULL,
  `DOC_TYPE` int(11) DEFAULT NULL,
  `DOC_LOCATION` varchar(300) DEFAULT NULL,
  `CREATED_AT` varchar(15) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `DOCUMENT_PAGES` (
  `DOCUMENT_ID` int(11) NOT NULL,
  `PAGE_INDEX` int(11) DEFAULT NULL,
  `IMAGE_URL` varchar(300) DEFAULT NULL,
  `PAGE_ID` varchar(45) DEFAULT NULL,
  `DOC_TYPE` varchar(45) DEFAULT NULL,
  `PAGE_DATA` json DEFAULT NULL,
  `OCR_BY` varchar(45) DEFAULT NULL,
  `PAGE_TEXT` text,
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `PAGE_BOXES` (
  `PAGE_ID` int(11) NOT NULL,
  `BOX_INDEX` int(11) DEFAULT NULL,
  `BOX_ID` int(11) DEFAULT NULL,
  `BOX_DATA` varchar(45) DEFAULT NULL,
  `BOX_LOCATION` varchar(100) DEFAULT NULL,
  `CLASS_TYPE` int(4) DEFAULT NULL,
  `BOX_TEXT` text,
  PRIMARY KEY (`PAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

/* ================================================================= */

CREATE TABLE `INVOICES` (
  `ID` int(11) NOT NULL,
  `INVOICE_NO` varchar(45) DEFAULT NULL,
  `INVOICE_DATE` varchar(45) DEFAULT NULL,
  `CUSTOMER_ID` varchar(45) DEFAULT NULL,
  `CUSTOMER_SEQ` int(11) DEFAULT NULL,
  `SELLER_ID` varchar(45) DEFAULT NULL,
  `CONSIGNEE_ID` varchar(45) DEFAULT NULL,
  `ETD` int(20) DEFAULT NULL,
  `ETD_TIMEZONE` varchar(45) DEFAULT NULL,
  `ETA` int(20) DEFAULT NULL,
  `ETA_TIMEZONE` varchar(45) DEFAULT NULL,
  `PO_NUMBER` varchar(45) DEFAULT NULL,
  `TIMESTAMP` varchar(20) DEFAULT NULL,
  `UPLOADED_BY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INVOICE_IDX` (`INVOICE_NO`),
  KEY `CUSTOMER_IDX` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `LINE_ITEMS` (
  `ID` int(11) NOT NULL,
  `INVOICE_ID` varchar(11) DEFAULT NULL,
  `ROW_ID` int(11) DEFAULT NULL,
  `SKU` varchar(45) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UNIT_PRICE` varchar(10) DEFAULT NULL,
  `CURRENCY` varchar(10) DEFAULT NULL,
  `QTY` varchar(45) DEFAULT NULL,
  `TOTAL_PRICE` varchar(45) DEFAULT NULL,
  `WEIGHT` varchar(45) DEFAULT NULL,
  `VOLUME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

/* ================================================================= */

CREATE TABLE `PARTIES` (
  `ID` int(11) NOT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `PARTY_NAME` varchar(80) DEFAULT NULL,
  `PARTY_TYPE` int(2) DEFAULT NULL,
  `STREET_ADDRESS` varchar(45) DEFAULT NULL,
  `OTHER_ADDRESS` varchar(200) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(20) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `CREATED_AT` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `TIME_ZONES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRY_CODE` varchar(45) DEFAULT NULL,
  `COUNTRY_NAME` varchar(45) DEFAULT NULL,
  `ZONE_NAME` varchar(45) DEFAULT NULL,
  `GMT_OFFSET` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=426 DEFAULT CHARSET=utf8

